<?php

declare(strict_types=1);

/*
 * This file is part of a F76 project.
 *
 * (c) Lorenzo Marozzo <lorenzo.marozzo@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260225130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add admin audit log table for sensitive admin actions';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on postgresql.',
        );

        $this->addSql('CREATE TABLE admin_audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, actor_user_id INT NOT NULL, target_user_id INT DEFAULT NULL, action VARCHAR(64) NOT NULL, context JSON DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_admin_audit_log_actor_user ON admin_audit_log (actor_user_id)');
        $this->addSql('CREATE INDEX idx_admin_audit_log_target_user ON admin_audit_log (target_user_id)');
        $this->addSql('CREATE INDEX idx_admin_audit_log_action ON admin_audit_log (action)');
        $this->addSql('CREATE INDEX idx_admin_audit_log_occurred_at ON admin_audit_log (occurred_at)');
        $this->addSql('ALTER TABLE admin_audit_log ADD CONSTRAINT fk_admin_audit_log_actor_user FOREIGN KEY (actor_user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admin_audit_log ADD CONSTRAINT fk_admin_audit_log_target_user FOREIGN KEY (target_user_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on postgresql.',
        );

        $this->addSql('DROP TABLE admin_audit_log');
    }
}
