<?php

declare(strict_types=1);

/*
 * This file is part of a F76 project.
 *
 * (c) Lorenzo Marozzo <lorenzo.marozzo@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260226220000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add minerva rotation table for timeline and temporal status';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on postgresql.',
        );

        $this->addSql('CREATE TABLE minerva_rotation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, location VARCHAR(120) NOT NULL, list_cycle INT NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_minerva_rotation_starts_at ON minerva_rotation (starts_at)');
        $this->addSql('CREATE INDEX idx_minerva_rotation_ends_at ON minerva_rotation (ends_at)');
        $this->addSql('CREATE INDEX idx_minerva_rotation_list_cycle ON minerva_rotation (list_cycle)');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on postgresql.',
        );

        $this->addSql('DROP TABLE minerva_rotation');
    }
}
